### ISSUE TITLE
Naming appropriately source tarballs and (git) repos

### ISSUE THREAD

**Issue by tsirif** [bchretien/arch-ros-stacks#51]
Hello there! In the last update to 1.11.11-0 of vision_opencv, opencv-apps, image-geometry, cv-bridge indigo source packages are all being downloaded as `1.11.11-0.tar.gz`, so aur manager cannot differentiate between them and sha256sums are also different. Could you add `"${_dir}.tar.gz":: ` before the url string of source package in PKGBUILDs? (_dir is the var that you define at the line above)  

Same thing happens in ros-indigo-pr2_description.   

In general, I propose naming corresponding source files/folders appropriately as it is done for packages.  
 - For tarballs something like: `source("${pkgname}-${pkgver}.tar.gz"::"<url>")`, for `pkgname="ros-${distro}-${smallpkgname}"` as it is defined in PKGBUILD  
 - For git repos something like: `source("${pkgname}"::"git+<url>")`  

Thank you in advance

**Comment by bchretien** [comment]
Thanks, this will be done automatically for future updates.
