### ISSUE TITLE
Support packages that do not have a release repo

### ISSUE THREAD

**Issue by lopsided98** [bchretien/arch-ros-stacks#56]
Some packages do not have a release in repository, and therefore the script is unable to generate a PKGBUILD for them. I think it would be nice to support these packages as Arch VCS packages (with a "-git" suffix). I will look into this and submit a PR if I can get it working.

**Comment by lopsided98** [comment]
Looking into it more, it seems like this is a lot of work for just a few packages, so I might just try to get the maintainers to release the package I want, or release it myself.

**Comment by bchretien** [comment]
Indeed, asking the developers for releases seems like the better route. Bloom makes releasing ROS packages really easy.
