### ISSUE TITLE
rosserial packages for jade?

### ISSUE THREAD

**Issue by justbuchanan** [bchretien/arch-ros-stacks#62]
Hi,
I noticed that rosserial (-msgs, -client, -arduino, etc) are available for indigo, but not for jade.  Would it be possible to get this setup for jade?  I'm happy to put together a pull request if this is something you will include.  Thanks!

**Comment by justbuchanan** [comment]
I just read through the readme and think I have a good understanding of how this works now.  I'll close this issue, then send a pull request with rosserial hopefully tomorrow when I get around to it.

**Comment by bchretien** [comment]
Indeed, you can easily generate the packages you're interested in ;)
