### ISSUE TITLE
Having trouble using this tool

### ISSUE THREAD

**Issue by G-Pereira** [bchretien/arch-ros-stacks#66]
COMAND:

python2 import_catkin_packages.py --distro=melodic --output-directory=/home/gpereira/Documents/arch-ros-stacks/melodic message_filters

OUTPUT:

/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Loading set of previously updated packages: /tmp/import_catkin_packages/updated_packages_melodic.dump
Ignoring actionlib_msgs
Ignoring catkin
Ignoring common_msgs
Ignoring diagnostic_msgs
Ignoring geometry_msgs
Ignoring message_filters
Ignoring mk
Ignoring nav_msgs
Ignoring ros
Ignoring ros_comm
Ignoring rosbag
Ignoring rosbash
Ignoring sensor_msgs
Ignoring shape_msgs
Ignoring stereo_msgs
Ignoring trajectory_msgs
Ignoring urdfdom_py
Ignoring visualization_msgs
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

This doesn't upload to AUR

**Comment by zootboy** [comment]
You can install python2-certifi to get rid of the cert warnings.

>This doesn't upload to AUR

I'm not sure what you mean by this. The script doesn't upload anything to the AUR, that's something you have to do yourself after you build and test the PKGBUILDs.

**Comment by G-Pereira** [comment]
@zootboy I've read the source and it actually tries to make a git clone and then commits the PKGBUILD and then pushes it, but that part throws an error... :( @racko are you here?

**Comment by zootboy** [comment]
The import_catkin_packages.py script does not commit (except on the initial creation of the submodule to prevent some git errors) and never pushes any packages. This is intentional, and is explained in the readme: https://github.com/bchretien/arch-ros-stacks#aur-upload

So after you've built and tested the packages, you need to run at minimum a "git push" to commit to the AUR. If you're getting an error, please post the text of it along with what commands you ran to get it.

**Comment by G-Pereira** [comment]
That's it! Thanks!
